[env]
_.file = { path = '{{ env.HOME }}/.secrets.yaml', redact = true }

[settings]
always_keep_download = true
experimental = true

[settings.age]
key_file = '{{ env.XDG_CONFIG_HOME }}/sops/age/keys.txt'

[settings.python]
uv_venv_auto = true

[settings.sops]
age_key_file = '{{ env.XDG_CONFIG_HOME }}/sops/age/keys.txt'

[settings.status]
show_env = true
show_tools = true

[tools]
age = 'latest'
cargo-binstall = 'latest'
deno = 'latest'
erlang = 'latest'
gleam = 'latest'
go = 'latest'
node = { version = 'lts', postinstall = 'corepack enable' }
python = 'latest'
ruby = 'latest'
rust = 'latest'
sops = 'latest'
uv = 'latest'
