GEMINI_API_KEY: ENC[AES256_GCM,data:+GGkb3CUMzp+q/+OhlKVc6xWZcdFK0sBhVOyCP6iojBi1ozgiMrn,iv:D+mFDme4GMuwy51MMLgSspY1b4IUPmXT39QWmdNyvbI=,tag:7mrmGpFaP1aUEpY7yp9e3Q==,type:str]
OPENAI_API_KEY: ENC[AES256_GCM,data:3Rsic22Rz6eVAPs09c+CvcuvFVjvEr/SallSx5aDhWz7S7Ypa356GKaJU6s/6mG6zc4AX6+wFBDLT341xoOKS3CuYj7ne2RG8fCouM/RrC6KyZiSMjD+XesKXjs0u0eaJn1F5z4t/twUKgiIo1V7nmLqP8nnRqk5QwZwWb1eN30a1dMROyKsfn4p484PXbSb8HZf4EOhEQRR67G9jg2m0vFq9Qg=,iv:HeEQN24pFiaP41GyOfyPhvq31fy2DnaiEmR4Wa4vWSQ=,tag:sS1t519+gBNE0TQSZjwGZA==,type:str]
MOONSHOT_API_KEY: ENC[AES256_GCM,data:PvvK+Sy7tqFVVjdJD+/sX89xzFm58MHzm1ZpF9vHd6VAogsMXR0qY/52KfeZUjdDVu/J,iv:KUNlpb+xClBH/zhb/OUG+wzDZDxF2m6/ZkCPdFuEySg=,tag:GJI9ogBbKT2ozeO6QkQauQ==,type:str]
sops:
    age:
        - recipient: age1lqfem5fj0vu5esyv0jr5f0vhennw7e77w4cal0m4mtnu4tpu0p7sag3ghg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRUV1T1BqN1d4NXIwd3h6
            MzdidGRvV2xobVJEcy9uOEpKNlRySmFzV20wCmRUakNTSGkyb2Y4RVcyalpRdXJL
            eDRmMm9GVUV6eHE2cGxZN2pIYit6UTQKLS0tIEY3eFBkdHJMS0p4OEc2RFJRWkU4
            eEZIcGZoY2xBOE4zQlYwVk9RMzN6bTAKakiXcOHpI+KUodlsytHoE4FwHgXOz/RF
            vMZfczRmZGW+xymiQmwG9kLA8lPAV0u5yvaBlY+DH9ZkDPyecfKBlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T19:44:23Z"
    mac: ENC[AES256_GCM,data:ieEPuPPMkLNZzbSlOSJ3ck8dM+ArjolR4kfJd6KsR0GdQnoaf/dDqvOatq1F0/EenpPi02/30DyvVKAi2kP1KOAtO7FHpFv2suqfMVd6fmFVz/RlpVNU9F0cnP4HrDMVoBFYD/4NjJsiDZ5u5N82CYRROkGL7oaISI1olC9YTHA=,iv:7pPU28ximzLEC4DZXfWALWkERdvgpV1LNm82JNvIZPk=,tag:2TEFNTHCHBw4uDuLXX507A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
